### PR TITLE
Set run_exports max_pin to x.x

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

---

Follow-up to https://github.com/conda-forge/azure-core-cpp-feedstock/pull/11. Please approve/disapprove whether we should continue rolling out the `max_pin="x.x"` run exports to all the Azure SDK for C++ recipes

### CODE REVIEW

**Review by jjerphan — APPROVED** [review]

**Review by teo-tsirpanis — APPROVED** [review]
I suggest we do this only to `azure-core-cpp` and `azure-storage-common-cpp` for now, which are lower-level packages.

**Comment by jdblischak** [comment]
@teo-tsirpanis what about `azure-identity-cpp`?

**Comment by teo-tsirpanis** [comment]
I consider it to be a high-level package because it provides some user-facing functionality. Users don't usually specifically want to install `azure-core-cpp` or `azure-storage-common-cpp`.

**Comment by jdblischak** [comment]
Ok, I'm fine with this intermediate approach. We'll apply the stricter pins to azure-core-cpp and azure-storage-common-cpp for now and monitor how the next few releases go

**Pull request merged**
